
FROM quay.io/simbelmas/fedora-minimal:v43.35@sha256:c202c4a234b3792992d3cb7e1c763607a70c7514089ea208abeeef9805d257fc



LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/app:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /app \
    && chmod -R 700 /app \ 
    && chown -R app:app /app

RUN echo 'www-data:x:82:' >> /etc/group \
    && echo 'www-data:x:82:82::/www-data:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /www-data \
    && chmod -R 700 /www-data \ 
    && chown -R www-data:www-data /www-data

RUN  microdnf --nodocs --best -y install \
       nfs-utils \
       git less openssh curl \
       rsync \
       python3 python3-pip python3-setuptools python3-wheel \
       openssl libacl libattr \
       borgbackup \
       zsh \
       time \
       netcat \
       skopeo \
       jq yq \
       python3-kubernetes \
       python3-jinja2-cli python3-jinja2 \
       rclone \
       s3cmd \
        && microdnf clean all

RUN sed -i 's@^Include /etc/ssh@#Include /etc/ssh@' /etc/ssh/ssh_config
USER 1001

