FROM quay.io/simbelmas/fedora-minimal:v43.15@sha256:45a775cf72eea63ade511f8c628e71d95dda5b48224563f516e750d132942ea9

LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN microdnf --nodocs --best -y install socat \
    && microdnf clean all

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/app:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /app /app/creds /app/config \
    && chown -Rv app:app /app \
    && chmod -R 755 /app

USER 1001

ENTRYPOINT ["socat"]
CMD ["-h"]
