FROM quay.io/simbelmas/fedora-minimal:v43.34@sha256:db178032fcbfadeea24ca3fd8dbbd9292e2f894fa8f6e440728459394fbca7fe

LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN microdnf --nodocs --best -y install socat \
    && microdnf clean all

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/app:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /app /app/creds /app/config \
    && chown -Rv app:app /app \
    && chmod -R 755 /app

USER 1001

ENTRYPOINT ["socat"]
CMD ["-h"]
