FROM quay.io/simbelmas/fedora-minimal:v43.21@sha256:7d61831fb57726181ebfd93e279d396cf3e04516de4170a92214cba44edee2bc

LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN microdnf --nodocs --best -y install socat \
    && microdnf clean all

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/app:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /app /app/creds /app/config \
    && chown -Rv app:app /app \
    && chmod -R 755 /app

USER 1001

ENTRYPOINT ["socat"]
CMD ["-h"]
