FROM olareg.skh.spdnova.xyz/skh-infra-base:v43.35@sha256:ac833d8419074c386db7c31fc9ba1e61e08fcb500525ae3638161d3a7421cef9 AS Base

FROM Base
ENV KUBERNETES_MINOR_VERSION=1.34
## KUBERNETES_PATCH_VERSION: when empty follows fedora release lifecycle for patches
ENV KUBERNETES_PATCH_VERSION=""

RUN microdnf --nodocs -y install \
        python3 policycoreutils-python-utils \
        nvtop \
        cri-o${KUBERNETES_MINOR_VERSION}${KUBERNETES_PATCH_VERSION} kubernetes${KUBERNETES_MINOR_VERSION}${KUBERNETES_PATCH_VERSION} kubernetes${KUBERNETES_MINOR_VERSION}-kubeadm${KUBERNETES_PATCH_VERSION} \
        qemu-user-static qemu-user-binfmt &&\
    microdnf clean all

COPY ./config/modules.crio-o.conf /usr/etc/modules-load.d/cri-o.conf
COPY ./config/sysctl-kubernetes.conf /usr/etc/sysctl.d/kubernetes.conf
COPY ./config/profile.sh /usr/etc/profile.d/
RUN mkdir -p /usr/etc/kubernetes/{kube-api-config,fedora-kube.d} &&\
    echo "KUBERNETES_DESIRED_VERSION=${KUBERNETES_MINOR_VERSION}" > /usr/etc/kubernetes/fedora-kube.d/fedora-kube-cluster.conf 
COPY --chmod=0600 ./config/admission-control-config.yaml /usr/etc/kubernetes/kube-api-config/
COPY --chmod=0600 ./config/encryption-at-rest-configuration.yaml /usr/etc/kubernetes/kube-api-config/
COPY ./config/crio-bridge.conflist /usr/etc/cni/net.d/100-crio-bridge.conflist

COPY ./systemd-units/kubernetes-node-lifecycle.service /usr/lib/systemd/system/
COPY --chmod=0700 ./scripts/kube-node-postinstall /usr/sbin/
COPY --chmod=0700 ./scripts/manage_kubernetes_controlplane_lifecycle.sh /usr/local/lib/
COPY --chmod=0700 ./scripts/manage_kubernetes_worker_lifecycle.zsh /usr/local/lib/
COPY --chmod=0700 ./scripts/manage-node-lifecycle.zsh /usr/local/lib/



RUN ln -sv /usr/lib/systemd/system/kubelet.service /usr/etc/systemd/system/multi-user.target.wants/ &&\
    ln -sv /usr/lib/systemd/system/crio.service /usr/etc/systemd/system/multi-user.target.wants/ &&\
    ln -sv /usr/lib/systemd/system/kubernetes-node-lifecycle.service /usr/etc/systemd/system/multi-user.target.wants/ &&\
    ln -sv /usr/lib/systemd/system/bootc-fleetlock-fetch-upgrade.service /usr/etc/systemd/system/multi-user.target.wants/ &&\
    ln -sv /usr/lib/systemd/system/bootc-fleetlock-fetch-upgrade.timer /usr/etc/systemd/system/timers.target.wants/ &&\
    ln -vs /dev/null /usr/etc/systemd/system/bootc-fetch-apply-updates.timer &&\
    ln -vs /dev/null /usr/etc/systemd/system/bootc-fetch-apply-updates.service 

RUN mkdir -p /var/lib/kubelet/pods

## Gpu selinux
RUN echo 'd /var/run/cdi 0755 root root - system_u:object_r:container_file_t:s0' > /usr/lib/tmpfiles.d/cdi.conf