From quay.io/simbelmas/fedora-minimal:v44.2@sha256:1cef69e363d0259f73866a024958df4b4188ca32fcb65db978723b4e93ea2ed0 AS Base

From Base as Builder


RUN microdnf --nodocs --best -y install go \
    && microdnf clean all
RUN mkdir app && cd /app \
    && go install -v github.com/flatcar/fleetlock@latest \
    && ls -al

FROM Base

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/app:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /app \
    && chmod -R 755 /app \ 
    && chown -R app:app /app 

COPY --from=Builder --chmod=0755 /root/go/bin/fleetlock /usr/local/bin/fleetlockctl

USER 1001

WORKDIR /app

LABEL maintainer "Simon Belmas <slos@soket.fr>"

ENTRYPOINT ["fleetlockctl"]