#!/bin/ash -e
if [ "$(ls -1 /etc/phpkube/php-conf.d/*.ini | wc -l)" -gt 0 ] ; then
    cp -vf /etc/phpkube/php-conf.d/*.ini /etc/php8/conf.d
fi
if [ "$(ls -1 /etc/phpkube/fpm-conf.d/*.conf | wc -l)" -gt 0 ] ; then
    cp -vf /etc/phpkube/fpm-conf.d/*.conf /etc/php8/php-fpm.d/
fi

exec /usr/bin/php $*

 