[Service]
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/skh/ /home/skh
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/francois/ /home/francois
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/seaweedfs/ /home/seaweedfs