[Service]
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/get_pxe_fedora_bootc.zsh /var/srv/containers/pxe-utils/get_pxe_fedora_bootc.zsh
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/pxe-configuration-update-manager.zsh /var/srv/containers/pxe-utils/pxe-configuration-update-manager.zsh
