FROM olareg.skh.spdnova.xyz/skh-infra-base:v44.8@sha256:a74bbb174cc311e7e1468d281240b5334b56a227455c007d684b2f0bf1199d70 AS Base

FROM Base

RUN microdnf --nodocs --best -y install \
        python3 \
        rsync &&\
    microdnf clean all &&\
    rm -rf /run/dnf /var/cache/* /var/lib/dnf /var/log/dnf5.log

COPY --chmod=0755 scripts/rrsync /usr/local/bin/
COPY users/backup_users.conf /usr/lib/sysusers.d

## Pxe scripts and configurations
COPY --chmod=0644 config/alias-pxe.sh /etc/profile.d/
RUN mkdir -p /usr/local/share/gitea_ssh/.ssh &&\
    chown 0700 -R /usr/local/share/gitea_ssh 
COPY --chmod=0600 config/gitea_ssh_config /usr/local/share/gitea_ssh/.ssh/config
COPY --chmod=0600 config/gitea_known_hosts /usr/local/share/gitea_ssh/.ssh/known_hosts
COPY systemd-units/static-gitea-ssh.conf /usr/lib/systemd/system/update-static-files.service.d/

## Systemd PXE management
COPY systemd-units/var-srv-backup.automount /usr/lib/systemd/system/
COPY systemd-units/var-srv-backup.mount /usr/lib/systemd/system/
COPY systemd-units/pxe-configuration-generate-pxe-chain.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-generate-pxe-chain.timer /usr/lib/systemd/system/
COPY systemd-units/pxe-configuration-ipxe-server.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-manage-assets.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-update-manager.container /usr/share/containers/systemd/
COPY systemd-units/olareg.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-restart-ipxe-server.service /usr/lib/systemd/system/

## Enabling previous configuration in systemd
RUN --mount=type=tmpfs,target=/run \
    systemd-analyze verify "/usr/lib/systemd/system/var-srv-backup.automount" &&\
    systemctl enable var-srv-backup.automount &&\
    systemd-analyze verify "/usr/lib/systemd/system/pxe-configuration-generate-pxe-chain.timer" &&\
    systemctl enable pxe-configuration-generate-pxe-chain.timer


## Manage static files update
# users homedirs
## skh user
RUN mkdir -p /usr/local/share/skh/.ssh &&\
    chmod 0700 /usr/local/share/skh &&\
    chown 1001:1001 -R /usr/local/share/skh
COPY --chown=1001:1001 --chmod=0600 users/authorized_keys /usr/local/share/skh/.ssh/authorized_keys

##sync homedirs
COPY systemd-units/backup-users-homedirs.conf /usr/lib/systemd/system/update-static-files.service.d/

# pxe dirs
RUN mkdir -p /usr/local/share/containers/{pxe-utils,pxe,pxe-nginx,olareg} &&\
    chmod 0755 -R /usr/local/share/containers &&\
    chmod 0755 /usr/local/share/containers/{pxe-utils,pxe,pxe-nginx} &&\
    chmod 0755 /usr/local/share/containers/olareg &&\
    chown 1000:1000 /usr/local/share/containers/olareg

COPY --chown=root --chmod=0755 scripts/get_pxe_fedora_bootc.zsh /usr/local/share/containers/pxe-utils/
COPY --chown=root --chmod=0755 scripts/pxe-configuration-update-manager.zsh /usr/local/share/containers/pxe-utils/
COPY systemd-units/static-0-pxe-utils.conf /usr/lib/systemd/system/update-static-files.service.d/

RUN --mount=type=tmpfs,target=/run \
    systemd-analyze verify "/usr/lib/systemd/system/bootc-fetch-apply-updates.timer" &&\
    systemctl enable bootc-fetch-apply-updates.timer

RUN bootc container lint --fatal-warnings