FROM olareg.soket.fr/skh-infra-base:v0.24@sha256:0385bd370c6fa6960ac1597db0fc89201c620dab04bad979b850bb7921c31c58 AS Base

FROM Base

RUN microdnf --nodocs --best -y install \
        python3 \
        rsync &&\
    microdnf clean all

COPY --chmod=0755 scripts/rrsync /usr/local/bin/
COPY users/backup_users.conf /usr/lib/sysusers.d

## Pxe scripts and configurations
COPY --chmod=0644 config/alias-pxe.sh /usr/etc/profile.d/

## Systemd management
COPY systemd-units/var-srv-backup.automount /usr/lib/systemd/system/
COPY systemd-units/var-srv-backup.mount /usr/lib/systemd/system/
COPY systemd-units/pxe-configuration-generate-pxe-chain.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-generate-pxe-chain.timer /usr/lib/systemd/system/
COPY systemd-units/pxe-configuration-ipxe-server.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-manage-assets.container /usr/share/containers/systemd/
COPY systemd-units/pxe-configuration-update-manager.container /usr/share/containers/systemd/
COPY systemd-units/olareg.container /usr/share/containers/systemd/

RUN cd /usr/lib/systemd/system/multi-user.target.wants &&\
    ln -vs /usr/lib/systemd/system/var-srv-backup.automount /usr/etc/systemd/system/multi-user.target.wants/ &&\
    ln -vs /usr/lib/systemd/system/pxe-configuration-generate-pxe-chain.timer /usr/etc/systemd/system/multi-user.target.wants/

## Manage static files update
# users homedirs
## skh user
RUN mkdir -p /usr/local/share/skh/.ssh &&\
    chmod 0700 /usr/local/share/skh &&\
    chown 1001:1001 -R /usr/local/share/skh
COPY --chown=1001:1001 --chmod=0600 users/authorized_keys /usr/local/share/skh/.ssh/authorized_keys
## francois user
RUN mkdir -p /usr/local/share/francois/.ssh &&\
    chmod 0700 /usr/local/share/francois &&\
    chown 1002:1002 -R /usr/local/share/francois
COPY --chown=1002:1002 --chmod=0600 users/authorized_keys /usr/local/share/francois/.ssh/authorized_keys
COPY systemd-units/backup-users-homedirs.conf /usr/lib/systemd/system/update-static-files.service.d/

# pxe dirs
RUN mkdir -p /usr/local/share/containers/pxe-utils/ /usr/local/share/containers/pxe/ /usr/local/share/containers/olareg &&\
    chmod 0755 -R /usr/local/share/containers &&\
    chmod 0700 /usr/local/share/containers/olareg &&\
    chown 1000:1000 /usr/local/share/containers/olareg

COPY --chown=root --chmod=0755 scripts/get_pxe_fedora_bootc.zsh /usr/local/share/containers/pxe-utils/
COPY --chown=root --chmod=0755 scripts/pxe-configuration-update-manager.zsh /usr/local/share/containers/pxe-utils/
COPY systemd-units/static-pxe-utils.conf /usr/lib/systemd/system/update-static-files.service.d/

RUN ln -sv /usr/lib/systemd/system/bootc-fetch-apply-updates.timer /usr/etc/systemd/system/timers.target.wants/
