FROM olareg.soket.fr/fedora-bootc:41 AS Base

FROM Base

RUN microdnf --nodocs --best -y install \
        zsh \
        vim-enhanced tmux &&\
    microdnf clean all

## Users management
#Users homedir are only configured at install time and nnot on updates
COPY users/mgmt_user.conf /usr/lib/sysusers.d
RUN echo '%wheel        ALL=(ALL)       NOPASSWD: ALL' > /etc/sudoers.d/wheel_no_password &&\
    mkdir -p /var/home/mgr/.ssh &&\
    chmod 0700 /var/home/mgr &&\
    chown 1000:1000 -R /var/home/mgr
COPY --chown=1000:1000 --chmod=0600 users/authorized_keys /var/home/mgr/.ssh/authorized_keys
COPY --chown=1000:1000 --chmod=0600 users/.zshrc /var/home/mgr/.zshrc

COPY --chmod=0644 shell_utilities_functions.zsh /usr/local/lib/
COPY --chmod=0700 reboot-to-pxe-install /usr/local/sbin/

## Manage systemd services
COPY systemd-units/set-timezone.service /usr/lib/systemd/system/
RUN cd /usr/lib/systemd/system/multi-user.target.wants &&\
    ln -vrs ../set-timezone.service ./set-timezone.service
#RUN bootc container lint