FROM olareg.skh.spdnova.xyz/skh-infra-kube:v43.30@sha256:c7da57b4ca026dba97b373541c77d0eb0980b60f0f7e4a5eea4f1e771be07f31 AS Base

FROM Base
ENV CEPH_RELEASE=20.2.0

RUN curl --silent --output /usr/sbin/cephadm --location https://download.ceph.com/rpm-${CEPH_RELEASE}/el9/noarch/cephadm \
    && chmod 555 /usr/sbin/cephadm
RUN echo 'alias ceph=cephadm shell -- ceph' >>  /usr/etc/profile.d/ceph_alias.sh