FROM olareg.skh.spdnova.xyz/skh-infra-kube:v43.35@sha256:c41d4e7776b273e748ca074ce11dc05fedb807877313adc62bf73523751cc361 AS Base

FROM Base
ENV CEPH_RELEASE=20.2.0

RUN curl --silent --output /usr/sbin/cephadm --location https://download.ceph.com/rpm-${CEPH_RELEASE}/el9/noarch/cephadm \
    && chmod 555 /usr/sbin/cephadm
RUN echo 'alias ceph=cephadm shell -- ceph' >>  /etc/profile.d/ceph_alias.sh

RUN bootc container lint --fatal-warnings