FROM quay.io/fedora/fedora-minimal:42@sha256:aece8e33c92eceea863385342f954be979da9c51d7a0f3514bcb570d46f7ae3e

LABEL maintainer "Simon Belmas <slos@soket.fr>"

#RUN echo -e "fastestmirror=True\nmax_parallel_downloads=10" >> /etc/dnf/dnf.conf \


