FROM quay.io/fedora/fedora-minimal:43@sha256:79e2e0a464d518dc1b7c9a92a48fa610151617810d972cbab4b7efa54aae939e

LABEL maintainer "Simon Belmas <slos@soket.fr>"

#RUN echo -e "fastestmirror=True\nmax_parallel_downloads=10" >> /etc/dnf/dnf.conf \


