FROM quay.io/fedora/fedora-minimal:43@sha256:3da2b6914b81f694c2ce720dfa8b288e2e081e6523779b0ac702750ad7ac8236

LABEL maintainer "Simon Belmas <slos@soket.fr>"

#RUN echo -e "fastestmirror=True\nmax_parallel_downloads=10" >> /etc/dnf/dnf.conf \


