[Service]
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/mgr/ /home/mgr
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/subuid /etc/subuid
ExecStart=/usr/local/sbin/update-static-file /usr/local/share/subgid /etc/subgid