FROM quay.io/simbelmas/fedora-minimal:v44.18@sha256:36203893a6b3281ff15a0c239e7d3839a35199b80581bbea179766674ab5daee AS builder
RUN mkdir /target
RUN dnf -y --installroot=/target \
    --setopt=install_weak_deps=False \
    --use-host-config \
    install \
    imapfilter python3-jinja2-cli\
    && dnf --installroot=/target clean all

# Stage 2: Final image
FROM scratch
COPY --from=builder /target /

COPY --chmod=0444 run.lua /app/run.lua

USER 1001

ENTRYPOINT ["/usr/bin/imapfilter"]
CMD ["-c", "/app/run.lua"]
