FROM quay.io/simbelmas/fedora-minimal:v44.14@sha256:76d353ccd271e0e66426f57059752541dc2ad36a472eb97cd1970452e35a68c3 AS builder
RUN mkdir /target
RUN dnf -y --installroot=/target \
    --setopt=install_weak_deps=False \
    --use-host-config \
    install \
    imapfilter python3-jinja2-cli\
    && dnf --installroot=/target clean all

# Stage 2: Final image
FROM scratch
COPY --from=builder /target /

COPY --chmod=0444 run.lua /app/run.lua

USER 1001

ENTRYPOINT ["/usr/bin/imapfilter"]
CMD ["-c", "/app/run.lua"]
