FROM quay.io/simbelmas/fedora-minimal:v43.7@sha256:278ba5d3892629ef5699eef2074114a80356f34f9351c28bf0342bb880581677 AS builder
RUN mkdir /target
RUN dnf -y --installroot=/target \
    --setopt=install_weak_deps=False \
    --use-host-config \
    install \
    imapfilter python3-jinja2-cli\
    && dnf --installroot=/target clean all

# Stage 2: Final image
FROM scratch
COPY --from=builder /target /

COPY --chmod=0444 run.lua /app/run.lua

USER 1001

ENTRYPOINT ["/usr/bin/imapfilter"]
CMD ["-c", "/app/run.lua"]
