FROM quay.io/simbelmas/fedora-minimal:v43.38@sha256:7899f2c717d8e44768df6046bd23320c9edb58c948cf06d564081416189cd6bb

LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN microdnf --nodocs --best -y install nginx-mod-http-xslt-filter nginx-mod-http-image-filter tzdata \
    && microdnf clean all

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/var/www:/sbin/nologin' >> /etc/passwd \
    && mkdir -p /var/www \
    && chmod 755 /var/www \ 
    && chown -R app:app /var/www

RUN mkdir -p /var/lib/nginx/tmp /etc/nginx/kube \
    && cp -RL /usr/share/nginx/html /var/www/ \
    && chown -R app: /etc/nginx /var/lib/nginx /var/www \
    && chmod 777 /var/lib/nginx/tmp \
    && chmod a+rX /var/lib/nginx \

    #Configure logs and unprivileged access to files
    && sed -r 's#^(.*listen.*)80;$#\18080;#g' -i /etc/nginx/nginx.conf \
    && sed 's#^pid.*$#pid /tmp/nginx.pid;#' -i /etc/nginx/nginx.conf \
    && sed -r 's/^(user .*$)/#\1/g' -i /etc/nginx/nginx.conf \
    && sed -r 's#^error_log.*$#error_log /dev/stdout warn;#g' -i /etc/nginx/nginx.conf \
    && sed -r 's#^([\t ]*access_log).*$#\1 /dev/stdout combined;#g' -i  /etc/nginx/nginx.conf \
    && sed -r 's/([\t ]*)#.*(server_tokens ).*$/\1\2off;/' -i /etc/nginx/nginx.conf \
    && sed '/^ *server {/,/}/ s/^.*$/#&/' -i /etc/nginx/nginx.conf \
    && rm -rf /etc/nginx/default.d \

    #Point to kube configuration in /etc/kube to avoid giving permissions to all users to /etc/nginx/conf.d
    && ln -sf /etc/nginx/kube/default.conf /etc/nginx/conf.d/default.conf 

COPY site-default.conf /etc/nginx/kube/default.conf
COPY temp-dir.conf /etc/nginx/conf.d/00-temp-dir.conf

WORKDIR /var/www
USER 1001

EXPOSE 8080

STOPSIGNAL SIGTERM

ENTRYPOINT ["nginx", "-g", "daemon off;"]


