server {                   
    listen       8080;
    error_log  /dev/stdout warn;
    access_log  /dev/stdout combined;
    server_name nginx;
    location / {
        try_files $uri $uri.html /index.html =404;
    }
    
    root /var/www/html/;
    server_tokens off;
}