# Stage 1: Build the rootfs
FROM quay.io/simbelmas/fedora-minimal:v44.20@sha256:2451bf821c027a5e426bd961817f5e0c8e377bda5b18ece5100b7be184bc25f5 AS builder
RUN mkdir /target
RUN dnf -y --installroot=/target \
    --setopt=install_weak_deps=False \
    --use-host-config \
    install \
    git-core git-crypt ca-certificates \
    && dnf --installroot=/target clean all

# Stage 2: Final image
FROM scratch
COPY --from=builder /target /
ENV GIT_SSH_COMMAND="ssh -i /ssh/ssh-privatekey -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/ssh/known_hosts"
RUN rm /etc/ssh/ssh_config.d/* || echo "no additional ssh config files to delete" \
    && echo 'app:x:1001:1001::/tmp:/sbin/nologin' >> /etc/passwd 
USER 65534
ENTRYPOINT ["/usr/bin/git"]
CMD ["--help"]