server {                   
    listen       8080;
    error_log  /dev/stdout warn;
    access_log  /dev/stdout combined;
    server_name ipxe;
    location / {
        try_files $uri /pxe/machine-default.ipxe =200;
    }
    
    root /var/www/html/;
    server_tokens off;
}