FROM quay.io/fedora/fedora-bootc:41@sha256:d312b7d03dda8c58d0f7cbaca93257cdd15d2248b21431f4d2d3a664b8fc2cf2 AS Base

FROM Base

RUN microdnf --nodocs --best -y install \
        zsh \
        rsync \
        vim-enhanced tmux &&\
    microdnf clean all

RUN rm -rvf /opt &&\
    ln -s /var/opt /opt &&\
    mkdir -p /usr/etc/systemd/system/multi-user.target.wants/

# Copy RO configuration files and scripts
COPY --chmod=0644 scripts/shell_utilities_functions.zsh /usr/local/lib/
COPY --chmod=0700 scripts/pxe-install /usr/local/sbin/
COPY --chmod=0644 config/sysctl-ipv6.conf /usr/etc/sysctl.d/ipv6.conf
COPY --chmod=0644 config/zz-default-editor.sh /usr/etc/profile.d/
COPY --chmod=0700 scripts/update-static-file /usr/local/sbin/
COPY --chmod=0700 scripts/bootc-fleetlock-fetch-apply-upgrade /usr/local/sbin/

## Manage systemd services
COPY systemd-units/set-timezone.service /usr/lib/systemd/system/
COPY systemd-units/update-static-files.service /usr/lib/systemd/system/
RUN mkdir /usr/lib/systemd/system/update-static-files.service.d &&\
    ln -s /usr/lib/systemd/system/set-timezone.service /usr/etc/systemd/system/multi-user.target.wants/ &&\
    ln -s /usr/lib/systemd/system/update-static-files.service /usr/etc/systemd/system/multi-user.target.wants/

## Manage static files update
COPY --chown=root --chmod=0644 config/chrony.conf /usr/etc/chrony.conf
COPY --chown=root --chmod=0644 config/skh-infra-registries.conf /usr/etc/containers/registries.conf.d/skh-infra-registries.conf

## Users management
COPY users/mgmt_user.conf /usr/lib/sysusers.d
RUN mkdir /usr/etc/sudoers.d &&\
    echo '%wheel        ALL=(ALL)       NOPASSWD: ALL' > /usr/etc/sudoers.d/wheel_no_password &&\
    mkdir -p /usr/local/share/mgr/.ssh &&\
    chmod 0700 /usr/local/share/mgr &&\
    chown 1000:1000 -R /usr/local/share/mgr &&\
    echo 'mgr:524288:65536' >> /usr/local/share/subuid &&\
    cp /usr/local/share/subuid /usr/local/share/subgid
COPY --chown=1000:1000 --chmod=0600 users/authorized_keys /usr/local/share/mgr/.ssh/authorized_keys
COPY --chown=1000:1000 --chmod=0600 users/.zshrc /usr/local/share/mgr/.zshrc
COPY systemd-units/mgr-user.conf /usr/lib/systemd/system/update-static-files.service.d/



#RUN bootc container lint