FROM quay.io/fedora/fedora-bootc:44@sha256:80fb64e560dfa8c3f600765acda06b0a3841cbd57a7f5e8de1f620c77c625708 AS Base

FROM Base

RUN dnf5 --nodocs --best -y install \
        zsh \
        rsync \
        vim-enhanced tmux &&\
    dnf5 clean all \
    && rm -rf /run/dnf /var/cache/* /var/lib/dnf /var/log/dnf5.log

# Copy RO configuration files and scripts
COPY --chmod=0644 scripts/shell_utilities_functions.zsh /usr/local/lib/
COPY --chmod=0700 scripts/pxe-install /usr/local/sbin/
COPY --chmod=0644 config/sysctl-ipv6.conf /usr/lib/sysctl.d/ipv6.conf
COPY --chmod=0644 config/zz-default-editor.sh /etc/profile.d/
COPY --chmod=0644 config/journald.conf /etc/systemd/journald.conf
COPY --chmod=0700 scripts/update-static-file /usr/local/sbin/
COPY --chmod=0700 scripts/bootc-fleetlock-fetch-apply-upgrade /usr/local/sbin/
COPY --chmod=0700 scripts/post-install-hook.zsh /usr/libexec/


## Manage systemd services
COPY systemd-units/set-timezone.service /usr/lib/systemd/system/
COPY systemd-units/update-static-files.service /usr/lib/systemd/system/
COPY systemd-units/bootc-fleetlock-fetch-upgrade.service /usr/lib/systemd/system/
COPY systemd-units/bootc-fleetlock-fetch-upgrade.timer /usr/lib/systemd/system/
COPY systemd-units/pxe-post-install.service /usr/lib/systemd/system/

RUN systemctl enable set-timezone.service &&\
    systemctl enable update-static-files.service &&\
    systemctl enable pxe-post-install.service


## Manage static files update
COPY --chown=root --chmod=0644 config/chrony.conf /etc/chrony.conf
COPY --chown=root --chmod=0644 config/skh-infra-registries.conf /etc/containers/registries.conf.d/skh-infra-registries.conf

## Users management
COPY users/mgmt_user.conf /usr/lib/sysusers.d
RUN echo '%wheel        ALL=(ALL)       NOPASSWD: ALL' > /etc/sudoers.d/wheel_no_password &&\
    mkdir -p /usr/local/share/mgr/.ssh &&\
    chmod 0700 /usr/local/share/mgr &&\
    chown 1000:1000 -R /usr/local/share/mgr &&\
    echo 'mgr:524288:65536' >> /usr/local/share/subuid &&\
    cp /usr/local/share/subuid /usr/local/share/subgid
COPY --chown=1000:1000 --chmod=0600 users/authorized_keys /usr/local/share/mgr/.ssh/authorized_keys
COPY --chown=1000:1000 --chmod=0600 users/.zshrc /usr/local/share/mgr/.zshrc
COPY systemd-units/static-0-mgr-user.conf /usr/lib/systemd/system/update-static-files.service.d/

# Fix registries missconfiguration
COPY systemd-units/static-force-registry-conf-upgrade.conf /usr/lib/systemd/system/update-static-files.service.d/

# Disable ssd sleep
COPY config/bootc-karggs-nvmve-config.toml /usr/lib/bootc/kargs.d/nvme-sleep.toml

#RUN systemd-sysusers &&\
#    echo 'mgr:test' | chpasswd 

RUN bootc container lint --fatal-warnings