FROM quay.io/simbelmas/adguardhome:dockerio-latest-mirror@sha256:927dc14b3e3cbd359e84658914590270a77d54446a6565e9498bef3444c286a4

RUN addgroup -g 1001 adguard \
    && adduser -G adguard -D -H -h /opt/adguardhome -u 1001 -s /bin/nologin adguard \
    && chown -Rv 1001:1001 /opt/adguardhome

USER 1001

LABEL maintainer "Simon Belmas <slos@soket.fr"
