FROM quay.io/simbelmas/adguardhome:dockerio-latest-mirror@sha256:f793df60142d249f2b869e95da4516acb96104aaa799bc3efb090622964242bd

RUN addgroup -g 1001 adguard \
    && adduser -G adguard -D -H -h /opt/adguardhome -u 1001 -s /bin/nologin adguard \
    && chown -Rv 1001:1001 /opt/adguardhome

USER 1001

LABEL maintainer "Simon Belmas <slos@soket.fr"
