FROM quay.io/simbelmas/fedora-minimal:v44.26@sha256:7f56bb2f782d8fbdc84b07cf0f5d058ca2e07ea45492dace3b2cbdb93a00dcbc

LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN microdnf --nodocs --best -y install mariadb mariadb-server mariadb-client-utils

RUN set -x \
    && userdel mysql \
    && groupadd -g 1001 mysql \
    && useradd --gid mysql -d /var/lib/mysql -u 1001 -s /bin/nologin mysql \
    && mkdir -p /var/run/mysqld /etc/my.cnf.kube.d /etc/mysql/mariadb.conf.d \
    && ln -s /dev/stdout /var/log/map_stdout  \
    && ln -s /dev/stdout /var/log/map_stdout.err \
    && rm -rf /var/lib/mysql/* \
    && mkdir /var/lib/mysql/data \
    && chown -R mysql: /var/lib/mysql /run/mysqld /etc/mysql /etc/my.cnf.kube.d \
    && rm -rf /etc/my.cnf /etc/my.cnf.d /etc/mysql/*cnf

COPY container_mariadb.cnf /etc/my.cnf
COPY start_mariadb /usr/local/bin/start_mariadb

RUN chmod 755 /usr/local/bin/start_mariadb

USER 1001

ENTRYPOINT ["/usr/local/bin/start_mariadb","--skip-log-error"]
