FROM quay.io/simbelmas/fedora-minimal:v43.4@sha256:f2199e9f5d4fa87fe39aa86d008a76eef7712d5aef6c46724ff45b15fcebdb25

LABEL maintainer "Simon Belmas <slos@soket.fr>"
## Mariadb upgrade procedure
# Review supported Mariadb and os versions here: https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/installing-mariadb/binary-packages/mariadb-package-repository-setup-and-usage#mariadb-community-server-repository
# update MariaDB.repo + FROM directive accordingly
# update last-built-tag to reflect mariadb version.

COPY MariaDB.repo /etc/yum.repos.d/MariaDB.repo
RUN rpm --import https://mirrors.ircam.fr/pub/mariadb/yum/RPM-GPG-KEY-MariaDB
RUN microdnf --nodocs --best -y install MariaDB-server MariaDB-client MariaDB-backup MariaDB-common

RUN set -x \
    && userdel mysql \
    && groupadd -g 1001 mysql \
    && useradd --gid mysql -d /var/lib/mysql -u 1001 -s /bin/nologin mysql \
    && mkdir -p /var/run/mysqld /etc/my.cnf.kube.d /etc/mysql/mariadb.conf.d \
    && ln -s /dev/stdout /var/log/map_stdout  \
    && ln -s /dev/stdout /var/log/map_stdout.err \
    && rm -rf /var/lib/mysql/* \
    && mkdir /var/lib/mysql/data \
    && chown -R mysql: /var/lib/mysql /run/mysqld /etc/mysql /etc/my.cnf.kube.d \
    && rm -rf /etc/my.cnf /etc/my.cnf.d /etc/mysql/*cnf

COPY container_mariadb.cnf /etc/my.cnf
COPY start_mariadb /usr/local/bin/start_mariadb

RUN chmod 755 /usr/local/bin/start_mariadb

USER 1001

ENTRYPOINT ["/usr/local/bin/start_mariadb","--skip-log-error"]
