FROM quay.io/simbelmas/fedora-minimal:v43.2@sha256:4377ed82a0df4cd3d9921a478bab047ee67a4bd667f0d913ab7e60d2ebacc055

LABEL maintainer "Simon Belmas <slos@soket.fr>"

COPY MariaDB.repo /etc/yum.repos.d/MariaDB.repo
RUN rpm --import https://mirrors.ircam.fr/pub/mariadb/yum/RPM-GPG-KEY-MariaDB
RUN microdnf --nodocs --best -y install MariaDB-server MariaDB-client MariaDB-backup MariaDB-common

RUN set -x \
    && userdel mysql \
    && groupadd -g 1001 mysql \
    && useradd --gid mysql -d /var/lib/mysql -u 1001 -s /bin/nologin mysql \
    && mkdir -p /var/run/mysqld /etc/my.cnf.kube.d /etc/mysql/mariadb.conf.d \
    && ln -s /dev/stdout /var/log/map_stdout  \
    && ln -s /dev/stdout /var/log/map_stdout.err \
    && chown -R mysql: /var/lib/mysql /run/mysqld /etc/mysql /etc/my.cnf.kube.d \
    && rm -rf /etc/my.cnf /etc/my.cnf.d /etc/mysql/*cnf

COPY container_mariadb.cnf /etc/my.cnf
COPY start_mariadb /usr/local/bin/start_mariadb

RUN chmod 755 /usr/local/bin/start_mariadb

USER 1001

ENTRYPOINT ["/usr/local/bin/start_mariadb","--skip-log-error"]
