FROM quay.io/simbelmas/fedora-minimal:v44.4@sha256:26983817928717e4c74508df084ffcd63951ac06d7d2682a986c08d88c49b780 AS Builder

## install build tools and libraries
RUN microdnf --setopt=install_weak_deps=false --nodocs --best -y install python3-pip python3-virtualenv unzip wget gcc \
     libxml2 libxml2-devel libxslt libxslt-devel \
     python3.12 python3.12-devel

RUN mkdir /venv /build \
    && virtualenv -p python3.12 /venv

ENV PATH=/venv/bin:$PATH

WORKDIR /build
## Grab release
RUN export bazarr_release=$(wget -q https://github.com/morpheus65535/bazarr/releases/latest -O - | grep "title>Release" | cut -d " " -f 4) \
    && export download_url="https://github.com/morpheus65535/bazarr/releases/download/${bazarr_release}/bazarr.zip" \
    && echo -n 'Will download from:' ; echo ${download_url} | tee software_downloaded_from \
    && wget -O Bazarr.zip "${download_url}"

###Install  Bazarr
RUN  unzip Bazarr.zip \
     && rm Bazarr.zip

RUN python --version \
    && pip install -r requirements.txt

FROM quay.io/simbelmas/fedora-minimal:v44.4@sha256:26983817928717e4c74508df084ffcd63951ac06d7d2682a986c08d88c49b780

LABEL maintainer "Simon Belmas <slos@soket.fr>"

RUN microdnf --setopt=install_weak_deps=false --nodocs -y install python3.12 unar ffmpeg-free\
    && microdnf clean all

COPY --from=Builder /venv /venv
COPY --from=Builder /build /app
ENV PATH=/venv/bin:$PATH

RUN echo 'app:x:1001:' >> /etc/group \
    && echo 'app:x:1001:1001::/app:/sbin/nologin' >> /etc/passwd

WORKDIR /opt/mediaData
USER 1001

ENTRYPOINT ["python","/app/bazarr.py"]
CMD ["--no-update", "-c", "/opt/mediaData"]



