[[registry]]
insecure = false
blocked = false
location = "olareg.skh.spdnova.xyz"

[[registry.mirror]]
location = "filia.skh.spdnova.xyz:5000"
insecure = true

[[registry]]
insecure = false
blocked = false
location = "quay.io/simbelmas"

[[registry.mirror]]
location = "olareg.skh.spdnova.xyz"