[[registry]]
prefix = "*.olareg.soket.fr"
insecure = false
blocked = false

[[registry.mirror]]
location = "filia.skh.soket.fr:5000"
insecure = true

[[registry]]
prefix = "quay.io/simbelmas"
insecure = false
blocked = false
location = "olareg.soket.fr"

[[registry.mirror]]
location = "quay.io/simbelmas"