#!/bin/zsh -e

source /usr/local/lib/shell_utilities_functions.zsh

if [[ -z "$1" ]] || [[ -z "$2" ]] || [[ "$1" == "help" ]] ; then
    echo "Source file and destination must be given." >&2
    exit 1
fi

update_file_if_changed "${1}" "${2}"

chmod --verbose --reference="${1}" "${2}"
chown --verbose --reference="${1}" "${2}"